//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Data Bag for the Insights block charts. */
export type InsightsChartOptionsBag = {
    /** Gets or sets the aspect ratio of the chart. */
    aspectRatio: number;

    /** Gets or sets the chart title. */
    chartTitle?: string | null;

    /** Gets or sets the type of the chart (e.g., bar, pie). */
    chartType?: string | null;

    /** Gets or sets a value indicating whether the chart legend is enabled. */
    isChartLegendEnabled: boolean;

    /** Gets or sets a value indicating whether the chart should maintain aspect ratio. */
    isMaintainAspectRatio: boolean;

    /** Gets or sets a value indicating whether the chart is responsive. */
    isResponsive: boolean;

    /** Gets or sets a value indicating whether the X axis legend is enabled. */
    isXLegendEnabled: boolean;

    /** Gets or sets a value indicating whether the Y axis legend is enabled. */
    isYLegendEnabled: boolean;

    /** Gets or sets the X axis title. */
    xTitle?: string | null;

    /** Gets or sets the maximum value for the Y axis. */
    yMax: number;

    /** Gets or sets the step size for the Y axis. */
    yStepSize: number;

    /** Gets or sets the Y axis title. */
    yTitle?: string | null;
};
