//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GridDataBag } from "@Obsidian/ViewModels/Core/Grid/gridDataBag";

/** The additional configuration options for the Financial Pledge Analytics block. */
export type FinancialPledgeAnalyticsBlockDataBag = {
    pledgeGridBox: { rows?: Record<string, unknown>[] | null | undefined; } | { then: <TResult1 = GridDataBag, TResult2 = never>(onfulfilled?: ((value: GridDataBag) => TResult1 | PromiseLike<TResult1>) | null | undefined, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined) => Promise<TResult1 | TResult2>; catch: <TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null | undefined) => Promise<GridDataBag | TResult>; finally: (onfinally?: (() => void) | null | undefined) => Promise<GridDataBag>; readonly [Symbol.toStringTag]: string; } | null | undefined;
    /** The data shown in the grid on the pledge tab */
    pledgeGridData?: GridDataBag | null
};
