//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using System.Collections.Generic;
using System.Net;

using Rock.Rest.Filters;
using Rock.Security;
using Rock.ViewModels.Core;
using Rock.ViewModels.Rest.Models;

namespace Rock.Rest.v2.Models
{
#if WEBFORMS
    using FromBodyAttribute = System.Web.Http.FromBodyAttribute;
    using IActionResult = System.Web.Http.IHttpActionResult;
    using RoutePrefixAttribute = System.Web.Http.RoutePrefixAttribute;
    using RouteAttribute = System.Web.Http.RouteAttribute;
    using HttpGetAttribute = System.Web.Http.HttpGetAttribute;
    using HttpPostAttribute = System.Web.Http.HttpPostAttribute;
    using HttpPutAttribute = System.Web.Http.HttpPutAttribute;
    using HttpPatchAttribute = System.Web.Http.HttpPatchAttribute;
    using HttpDeleteAttribute = System.Web.Http.HttpDeleteAttribute;
#else
    using Microsoft.AspNetCore.Mvc;

    using RoutePrefixAttribute = Microsoft.AspNetCore.Mvc.RouteAttribute;
#endif

    /// <summary>
    /// Provides data API endpoints for Contact Relationship Strength Changes.
    /// </summary>
    [RoutePrefix( "api/v2/models/contactrelationshipstrengthchanges" )]
    [Rock.SystemGuid.RestControllerGuid( "545e9c50-cc84-555d-a4c2-2b8c684bf316" )]
    public partial class ContactRelationshipStrengthChangesController : ApiControllerBase
    {
        /// <summary>
        /// Gets a single item from the database.
        /// </summary>
        /// <param name="id">The identifier as either an Id, Guid or IdKey value.</param>
        /// <returns>The requested item.</returns>
        [HttpGet]
        [Route( "{id}" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ProducesResponse( HttpStatusCode.OK, Type = typeof( Rock.Model.ContactRelationshipStrengthChanges ) )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "ddd9f5fd-9db2-5f20-85d1-efb8cf462d74" )]
        public IActionResult GetItem( string id )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.Get( id );
        }

        /// <summary>
        /// Creates a new item in the database.
        /// </summary>
        /// <param name="value">The item to be created.</param>
        /// <returns>An object that contains the new identifier values.</returns>
        [HttpPost]
        [Route( "" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ProducesResponse( HttpStatusCode.Created, Type = typeof( CreatedAtResponseBag ) )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "585c564a-70aa-5657-94ff-30d3a6818a78" )]
        public IActionResult PostItem( [FromBody] Rock.Model.ContactRelationshipStrengthChanges value )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.Create( value );
        }

        /// <summary>
        /// Performs a full update of the item. All property values must be
        /// specified.
        /// </summary>
        /// <param name="id">The identifier as either an Id, Guid or IdKey value.</param>
        /// <param name="value">The item that represents all the new values.</param>
        /// <returns>An empty response.</returns>
        [HttpPut]
        [Route( "{id}" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ProducesResponse( HttpStatusCode.NoContent )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "8c722cd8-fa35-57d5-86f7-fe96f696137e" )]
        public IActionResult PutItem( string id, [FromBody] Rock.Model.ContactRelationshipStrengthChanges value )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.Update( id, value );
        }

        /// <summary>
        /// Performs a partial update of the item. Only specified property keys
        /// will be updated.
        /// </summary>
        /// <param name="id">The identifier as either an Id, Guid or IdKey value.</param>
        /// <param name="values">An object that identifies the properties and values to be updated.</param>
        /// <returns>An empty response.</returns>
        [HttpPatch]
        [Route( "{id}" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ProducesResponse( HttpStatusCode.NoContent )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "3d7b1155-379f-540f-a632-9c3a5a2c3b0f" )]
        public IActionResult PatchItem( string id, [FromBody] Dictionary<string, object> values )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.Patch( id, values );
        }

        /// <summary>
        /// Gets all the attribute values for the specified item.
        /// </summary>
        /// <param name="id">The identifier as either an Id, Guid or IdKey value.</param>
        /// <returns>An array of objects that represent all the attribute values.</returns>
        [HttpGet]
        [Route( "{id}/attributevalues" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ProducesResponse( HttpStatusCode.OK, Type = typeof( Dictionary<string, ModelAttributeValueBag> ) )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "cbcc8c9c-4d61-5f6b-b5a1-e2a9035e27b6" )]
        public IActionResult GetAttributeValues( string id )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.GetAttributeValues( id );
        }

        /// <summary>
        /// Performs a partial update of attribute values for the item. Only
        /// attributes specified will be updated.
        /// </summary>
        /// <param name="id">The identifier as either an Id, Guid or IdKey value.</param>
        /// <param name="values">An object that identifies the attribute keys and raw values to be updated.</param>
        /// <returns>An empty response.</returns>
        [HttpPatch]
        [Route( "{id}/attributevalues" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ProducesResponse( HttpStatusCode.NoContent )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "746ed801-4720-5402-9130-e9187f3da679" )]
        public IActionResult PatchAttributeValues( string id, [FromBody] Dictionary<string, string> values )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = true;

            return helper.PatchAttributeValues( id, values );
        }

        /// <summary>
        /// Performs a search of items using the specified user query.
        /// </summary>
        /// <param name="query">Query options to be applied.</param>
        /// <returns>An array of objects returned by the query.</returns>
        [HttpPost]
        [Route( "search" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_UNRESTRICTED_READ )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_READ, Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ProducesResponse( HttpStatusCode.OK, Type = typeof( object ) )]
        [SystemGuid.RestActionGuid( "d9ef92ab-31d4-579b-8388-fe390f86341e" )]
        public IActionResult PostSearch( [FromBody] EntitySearchQueryBag query )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            return helper.Search( query );
        }

        /// <summary>
        /// Performs a search of items using the specified system query.
        /// </summary>
        /// <param name="searchKey">The key that identifies the entity search query to execute.</param>
        /// <returns>An array of objects returned by the query.</returns>
        [HttpGet]
        [Route( "search/{searchKey}" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_READ )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ProducesResponse( HttpStatusCode.OK, Type = typeof( object ) )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "eac4a925-83ed-504f-9881-87a54cd4dfdc" )]
        public IActionResult GetSearchByKey( string searchKey )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = IsCurrentPersonAuthorized( Security.Authorization.EXECUTE_UNRESTRICTED_READ );

            return helper.Search( searchKey, null );
        }

        /// <summary>
        /// Performs a search of items using the specified system query.
        /// </summary>
        /// <param name="query">Additional query refinement options to be applied.</param>
        /// <param name="searchKey">The key that identifies the entity search query to execute.</param>
        /// <returns>An array of objects returned by the query.</returns>
        [HttpPost]
        [Route( "search/{searchKey}" )]
        [Authenticate]
        [Secured( Security.Authorization.EXECUTE_READ )]
        [ExcludeSecurityActions( Security.Authorization.EXECUTE_WRITE, Security.Authorization.EXECUTE_UNRESTRICTED_WRITE )]
        [ProducesResponse( HttpStatusCode.OK, Type = typeof( object ) )]
        [ProducesResponse( HttpStatusCode.BadRequest )]
        [ProducesResponse( HttpStatusCode.NotFound )]
        [ProducesResponse( HttpStatusCode.Unauthorized )]
        [SystemGuid.RestActionGuid( "e026b690-b27b-58d2-ab23-9b1f22bcbe70" )]
        public IActionResult PostSearchByKey( string searchKey, [FromBody] EntitySearchQueryBag query )
        {
            var helper = new CrudEndpointHelper<Rock.Model.ContactRelationshipStrengthChanges, Rock.Model.ContactRelationshipStrengthChangesService>( this );

            helper.IsSecurityIgnored = IsCurrentPersonAuthorized( Security.Authorization.EXECUTE_UNRESTRICTED_READ );

            return helper.Search( searchKey, query );
        }
    }
}
