//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { BenevolenceResultBag } from "@Obsidian/ViewModels/Blocks/Finance/BenevolenceRequestDetail/benevolenceResultBag";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

/** The item details for the Benevolence Request Detail block. */
export type BenevolenceRequestBag = {
    /** Gets or sets the attributes. */
    attributes?: Record<string, PublicAttributeBag> | null;

    /** Gets or sets the attribute values. */
    attributeValues?: Record<string, string> | null;

    /** Gets or sets a collection of BenevolenceResults */
    benevolenceResults?: ListItemBag[] | null;

    /** Gets or sets the benevolence type. */
    benevolenceType?: ListItemBag | null;

    /** Gets or sets the benevolence type identifier. */
    benevolenceTypeId: number;

    /** Gets or sets the Rock.Model.Campus that this Benevolence Request is associated with. */
    campus?: ListItemBag | null;

    /** Gets or sets the campus identifier. */
    campusId?: number | null;

    /** Gets or sets the case worker Rock.Model.PersonAlias. */
    caseWorkerPersonAlias?: ListItemBag | null;

    /** Gets or sets the PersonAliasId of the Rock.Model.PersonAlias who is the case worker for this request. */
    caseWorkerPersonAliasId?: number | null;

    /** Gets or sets the Cell Phone Number of the person who requested benevolence. */
    cellPhoneNumber?: string | null;

    /** Gets or sets the Rock.Model.DefinedValue representing the Requester's connection status. */
    connectionStatusValue?: ListItemBag | null;

    /** Gets or sets the Id of the Defined Value Rock.Model.DefinedValue representing the connection status of the Requester. */
    connectionStatusValueId?: number | null;

    /** Gets or sets the documents. */
    documents?: ListItemBag[] | null;

    /** Gets or sets the email address of the person requesting benevolence. */
    email?: string | null;

    /** Gets or sets the First Name of the person that this benevolence request is about. This property is required. */
    firstName?: string | null;

    /** Gets or sets the GovernmentId of the person who requested benevolence. */
    governmentId?: string | null;

    /** Gets or sets the Home Phone Number of the person who requested benevolence. */
    homePhoneNumber?: string | null;

    /** Gets or sets the identifier key of this entity. */
    idKey?: string | null;

    /** Gets or sets the Last Name of the person that this benevolence request is about. This property is required. */
    lastName?: string | null;

    /** Gets or sets the Rock.Model.Location that is associated with this Benevolence Request. */
    location?: ListItemBag | null;

    /** Gets or sets the Id of the Rock.Model.Location that is associated with this BenevolenceRequest. */
    locationId?: number | null;

    /** Gets or sets the provided next steps. */
    providedNextSteps?: string | null;

    /** Gets the request date key. */
    requestDateKey: number;

    /** Gets or sets the date that this benevolence request was entered. */
    requestDateTime?: string | null;

    /** Gets or sets the requested by Rock.Model.PersonAlias. */
    requestedByPersonAlias?: ListItemBag | null;

    /** Gets or sets the PersonAliasId of the Rock.Model.PersonAlias who is submitting the BenevolenceRequest */
    requestedByPersonAliasId?: number | null;

    /** Gets or sets the Rock.Model.DefinedValue representing the Benevolence Request's status. */
    requestStatusValue?: ListItemBag | null;

    /** Gets or sets the Id of the Defined Value Rock.Model.DefinedValue representing the status of the Benevolence Request. */
    requestStatusValueId?: number | null;

    /** Gets or sets the text/content of the request. */
    requestText?: string | null;

    /** Gets or sets the collection of benevolence results. */
    results?: BenevolenceResultBag[] | null;

    /** Gets or sets the summary of the request result. */
    resultSummary?: string | null;

    /** Gets or sets the Work Phone Number of the person who requested benevolence. */
    workPhoneNumber?: string | null;
};
