//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { CategoryTreeViewTreeListBag } from "@Obsidian/ViewModels/Blocks/Core/CategoryTreeView/categoryTreeViewTreeListBag";

/** Initialization bag returned to the frontend */
export type CategoryTreeViewBag = {
    /** Gets or sets the error message to be displayed to the user, if any. */
    errorMessage?: string | null;

    /** Gets or sets a value indicating whether the category type is activated. */
    isActivatedType: boolean;

    /** Gets or sets a value indicating whether the category tree is editable by the current user. */
    isEditable: boolean;

    /** Gets or sets a value indicating whether the user is hiding inactive items in the category tree. */
    isUserHidingInactiveItems: boolean;

    /** Gets or sets the tree list containing the category tree structure. */
    treeList?: CategoryTreeViewTreeListBag | null;
};
