//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";
import { TreeItemBag } from "@Obsidian/ViewModels/Utility/treeItemBag";

/** Represents the data structure for a tree list in the Category Tree View block. */
export type CategoryTreeViewTreeListBag = {
    /** Gets or sets the list of item GUIDs that are currently expanded. */
    expandedItems?: Guid[] | null;

    /** Gets or sets the list of item GUIDs that should be initially expanded. */
    initiallyExpandedItems?: Guid[] | null;

    /** Gets or sets a value indicating whether deselection is allowed. */
    isAllowingDeselection: boolean;

    /** Gets or sets a value indicating whether folder selection is disabled. */
    isFolderSelectionDisabled: boolean;

    /** Gets or sets a value indicating whether the child count is shown for each item. */
    isShowingChildCount: boolean;

    /** Gets or sets the collection of tree items to display. */
    items?: TreeItemBag[] | null;

    /** Gets or sets the list of selected item keys. */
    selectedItems?: string[] | null;
};
