//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Initialization bag returned to the frontend */
export type CategoryTreeViewBlockAttributesBag = {
    /** Gets or sets the default CSS class to use for icons in the tree view. */
    defaultIconCSSClass?: string | null;

    /** Gets or sets the page reference used to display the details of a selected category or entity. */
    detailPage?: string | null;

    /** Gets or sets the entity type name that this category tree is associated with. */
    entityType?: string | null;

    /** Gets or sets the friendly display name of the associated entity type. */
    entityTypeFriendlyName?: string | null;

    /** Gets or sets the qualifier property used to filter the entity type. */
    entityTypeQualifierProperty?: string | null;

    /** Gets or sets the qualifier value used to filter the entity type. */
    entityTypeQualifierValue?: string | null;

    /** Gets or sets a comma-delimited list of category identifiers to exclude from the tree view. */
    excludeCategories?: string | null;

    /** Gets or sets the key of the page parameter used to identify the selected entity. */
    pageParameterKey?: string | null;

    /** Gets or sets the identifier of the root category for the tree view. */
    rootCategory?: string | null;

    /** Gets or sets the page reference used to display search results. */
    searchResultsPage?: string | null;

    /** Gets or sets a value indicating whether only categories should be shown in the tree view. */
    showOnlyCategories: boolean;

    /** Gets or sets a value indicating whether unnamed entity items should be shown. */
    showUnnamedEntityItems: boolean;
};
