//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GroupTypeInheritedAttributeBag } from "@Obsidian/ViewModels/Blocks/Group/GroupTypeDetail/groupTypeInheritedAttributeBag";
import { PublicEditableAttributeBag } from "@Obsidian/ViewModels/Utility/publicEditableAttributeBag";

/** Response bag containing editable and inherited attributes for an entity type in the GroupTypeDetail block. */
export type GroupTypeGetAttributesResponseBag = {
    /** Gets or sets the editable Group attributes scoped to the current group type being edited. */
    groupAttributes?: PublicEditableAttributeBag[] | null;

    /** Gets or sets the editable GroupMember attributes scoped to the current group type being edited. */
    groupMemberAttributes?: PublicEditableAttributeBag[] | null;

    /** Gets or sets the editable GroupType attributes scoped to the current group type being edited. */
    groupTypeAttributes?: PublicEditableAttributeBag[] | null;

    /** Gets or sets the inherited Group attributes from the inherited group type chain (parent/grandparent/etc). */
    inheritedGroupAttributes?: GroupTypeInheritedAttributeBag[] | null;

    /** Gets or sets the inherited GroupMember attributes from the inherited group type chain (parent/grandparent/etc). */
    inheritedGroupMemberAttributes?: GroupTypeInheritedAttributeBag[] | null;

    /** Gets or sets the inherited GroupType attributes from the inherited group type chain (parent/grandparent/etc). */
    inheritedGroupTypeAttributes?: GroupTypeInheritedAttributeBag[] | null;
};
