<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Rock">
      <HintPath>..\Dependencies\Rock.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Rock.Common">
      <HintPath>..\Dependencies\Rock.Common.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Rock.Enums">
      <HintPath>..\Dependencies\Rock.Enums.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Rock.Rest">
      <HintPath>..\Dependencies\Rock.Rest.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="EntityFramework">
      <HintPath>..\Dependencies\EntityFramework.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\Dependencies\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>..\Dependencies\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>..\Dependencies\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
      <Private>true</Private>
    </Reference>

    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.ComponentModel.Composition" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Http">
      <HintPath>..\Dependencies\System.Web.Http.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="System.ComponentModel.DataAnnotations" />
  </ItemGroup>
</Project>
